# Generated by Django 4.1.3 on 2023-01-04 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dealt_with', models.BooleanField(default=False)),
                ('feedback_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changelog_text', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changelog_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
