# Generated by Django 4.0.6 on 2022-08-06 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_text', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticket_creator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
