# Generated by Django 4.0.6 on 2022-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
