# Generated by Django 4.0.6 on 2022-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_feedback_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
