# Generated by Django 4.1.3 on 2022-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_feedback_feedback_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
    ]
