# Generated by Django 4.1.3 on 2022-11-02 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_idempotencykeys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idempotencykeys',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='idempotencykeys',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
