# Generated by Django 4.1.3 on 2022-11-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_idempotencykeys_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idempotencykeys',
            options={'ordering': ['created']},
        ),
    ]
