# Generated by Django 4.1.3 on 2022-12-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_idempotencykeys_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdempotencyKeys',
        ),
    ]
