# Generated by Django 4.1.7 on 2023-07-23 21:09

import accounts.models
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_directory_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_url',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=10, prefix=''),
        ),
    ]
