# Generated by Django 4.1.3 on 2023-01-04 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import timelines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('name', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, default='', null=True)),
                ('position', models.IntegerField(default=9999)),
            ],
            options={
                'ordering': ['timeline', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('name', models.CharField(max_length=500)),
                ('position', models.IntegerField(default=9999)),
                ('position_episode', models.IntegerField(default=9999)),
            ],
            options={
                'ordering': ['timeline', 'position', 'position_episode'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('title', models.CharField(max_length=500)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=timelines.models.header_image_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='UserHasFinishedTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_as_finished', models.ManyToManyField(blank=True, to='timelines.entry')),
                ('mark_ep_as_finished', models.ManyToManyField(blank=True, to='timelines.episode')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_tracker', to='timelines.timeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to=timelines.models.image_directory_path)),
                ('position', models.IntegerField(default=9999)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='timelines.timeline')),
            ],
            options={
                'ordering': ['timeline', 'position'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='timelines.timeline'),
        ),
        migrations.AddField(
            model_name='entry',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='timelines.timeline'),
        ),
        migrations.CreateModel(
            name='Divider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('subheading', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('position', models.IntegerField(default=9999)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divider', to='timelines.timeline')),
            ],
            options={
                'ordering': ['timeline', 'position'],
            },
        ),
    ]
