# Generated by Django 4.0.6 on 2022-09-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='section',
        ),
    ]
