# Generated by Django 4.1.3 on 2023-01-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_episode_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='link',
        ),
    ]
