# Generated by Django 4.0.6 on 2022-09-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_remove_entry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='section',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
