# Generated by Django 4.1.3 on 2023-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_remove_episode_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='header_caption',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='header_source',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
