# Generated by Django 4.0.6 on 2022-09-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_entry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
