# Generated by Django 4.0.6 on 2022-09-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_entry_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='end_date',
        ),
    ]
