# Generated by Django 4.1.7 on 2023-03-18 22:29

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_image_source_timeline_header_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='url',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=10, prefix=''),
        ),
    ]
