# Generated by Django 4.1.7 on 2023-03-18 20:46

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_image_source_timeline_header_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='url',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=16, max_length=16, prefix=''),
        ),
    ]
