# Generated by Django 4.0.6 on 2022-09-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_rename_start_date_entry_date_remove_entry_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(blank=True, default='', max_length=500)),
                ('comment', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('position', models.IntegerField(default=1000)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='position',
        ),
        migrations.CreateModel(
            name='Divider',
            fields=[
                ('timelineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timelines.timelineitem')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divider', to='timelines.timeline')),
            ],
            options={
                'ordering': ['position'],
            },
            bases=('timelines.timelineitem',),
        ),
    ]
