# Generated by Django 4.1.7 on 2023-03-18 20:48

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_timeline_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='url',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=10, prefix=''),
        ),
    ]
