# Generated by Django 4.1.7 on 2023-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_alter_timeline_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
