# Generated by Django 4.0.6 on 2022-09-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0007_alter_entry_options_entry_comment_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='order',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
