# Generated by Django 4.0.6 on 2022-09-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0009_alter_timeline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='order',
            field=models.JSONField(blank=True, default='dict'),
        ),
    ]
