# Generated by Django 4.0.6 on 2022-09-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0012_divider'),
    ]

    operations = [
        migrations.AddField(
            model_name='divider',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
