# Generated by Django 4.0.6 on 2022-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0013_divider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='divider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='order',
        ),
        migrations.AddField(
            model_name='timeline',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
