# Generated by Django 4.0.6 on 2022-09-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0015_image_caption_image_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='timelines.timeline'),
        ),
        migrations.CreateModel(
            name='TimelineOrdering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1000)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_ordering', to='timelines.timeline')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='divider',
            name='ordering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelines.timelineordering'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ordering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelines.timelineordering'),
        ),
        migrations.AddField(
            model_name='image',
            name='ordering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timelines.timelineordering'),
        ),
    ]
