# Generated by Django 4.0.6 on 2022-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0017_remove_divider_ordering_remove_entry_ordering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=1000),
        ),
    ]
