# Generated by Django 4.0.6 on 2022-09-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0018_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
    ]
