# Generated by Django 4.0.6 on 2022-09-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0020_alter_divider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divider',
            name='position',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='entry',
            name='position',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=9999),
        ),
        migrations.CreateModel(
            name='SubEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.IntegerField(default=9999)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subentry', to='timelines.entry')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
