# Generated by Django 4.0.6 on 2022-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0021_alter_divider_position_alter_entry_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subentry',
            name='date',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subentry',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
