# Generated by Django 4.0.6 on 2022-09-30 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0022_subentry_date_alter_subentry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasReadSubEntryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tracker', to='timelines.entry')),
                ('mark_as_read', models.ManyToManyField(blank=True, to='timelines.subentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subentry_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
