# Generated by Django 4.0.6 on 2022-10-03 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0023_userhasreadsubentrytracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(blank=True, default='', max_length=500)),
                ('position', models.IntegerField(default=9999)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='timelines.entry')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserHasReadEpisodeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tracker', to='timelines.entry')),
                ('mark_as_read', models.ManyToManyField(blank=True, to='timelines.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userhasreadsubentrytracker',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='userhasreadsubentrytracker',
            name='mark_as_read',
        ),
        migrations.RemoveField(
            model_name='userhasreadsubentrytracker',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='SubEntry',
        ),
        migrations.DeleteModel(
            name='UserHasReadSubEntryTracker',
        ),
    ]
