# Generated by Django 4.0.6 on 2022-10-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0024_episode_userhasreadepisodetracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='header_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
