# Generated by Django 4.0.6 on 2022-10-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0026_alter_timeline_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='header_image',
            field=models.ImageField(null=True, upload_to='timeline_directory_path'),
        ),
    ]
