# Generated by Django 4.0.6 on 2022-10-04 00:53

from django.db import migrations, models
import timelines.models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0027_alter_timeline_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=timelines.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='header_image',
            field=models.ImageField(null=True, upload_to=timelines.models.header_image_directory_path),
        ),
    ]
