# Generated by Django 4.0.6 on 2022-10-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0029_alter_timeline_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divider',
            old_name='date',
            new_name='subheading',
        ),
    ]
