# Generated by Django 4.0.6 on 2022-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0030_rename_date_divider_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divider',
            name='comment',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
