# Generated by Django 4.0.6 on 2022-10-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0031_alter_divider_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divider',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='section',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
