# Generated by Django 4.0.6 on 2022-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0032_alter_divider_comment_alter_entry_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='description',
        ),
        migrations.AlterField(
            model_name='divider',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='divider',
            name='subheading',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
