# Generated by Django 4.0.6 on 2022-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0033_remove_timeline_description_alter_divider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
