# Generated by Django 4.1.2 on 2022-10-26 23:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0034_timeline_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHasReadEpisodeTracker',
            new_name='UserHasFinishedEpisodeTracker',
        ),
        migrations.RenameModel(
            old_name='UserHasReadTracker',
            new_name='UserHasFinishedTracker',
        ),
        migrations.RenameField(
            model_name='userhasfinishedepisodetracker',
            old_name='mark_as_read',
            new_name='mark_as_finished',
        ),
        migrations.RenameField(
            model_name='userhasfinishedtracker',
            old_name='mark_as_read',
            new_name='mark_as_finished',
        ),
    ]
