# Generated by Django 4.1.2 on 2022-11-01 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0036_delete_userhasfinishedepisodetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasReadEpisodeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tracker', to='timelines.entry')),
                ('mark_as_finished', models.ManyToManyField(blank=True, to='timelines.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
