# Generated by Django 4.1.3 on 2022-11-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0037_userhasreadepisodetracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHasReadEpisodeTracker',
        ),
    ]
