# Generated by Django 4.1.3 on 2022-11-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0038_delete_userhasreadepisodetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='timeline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='timelines.timeline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.entry'),
        ),
    ]
