# Generated by Django 4.1.3 on 2022-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0039_episode_timeline_alter_episode_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
