# Generated by Django 4.1.3 on 2022-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0040_episode_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='entry',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_position',
            field=models.IntegerField(default=9999),
        ),
    ]
