# Generated by Django 4.1.3 on 2022-11-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0041_remove_episode_entry_episode_episode_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode_position',
            new_name='position_episode',
        ),
    ]
