# Generated by Django 4.1.3 on 2022-11-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0042_rename_episode_position_episode_position_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['position_episode']},
        ),
    ]
