# Generated by Django 4.1.3 on 2022-12-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0043_alter_episode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhasfinishedtracker',
            name='mark_ep_as_finished',
            field=models.ManyToManyField(blank=True, to='timelines.episode'),
        ),
    ]
