# Generated by Django 4.1.3 on 2022-12-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0044_userhasfinishedtracker_mark_ep_as_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['position', 'position_episode']},
        ),
    ]
