# Generated by Django 4.1.3 on 2022-12-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0045_alter_episode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divider',
            options={'ordering': ['timeline', 'position']},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['timeline', 'position']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['timeline', 'position', 'position_episode']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['timeline', 'position']},
        ),
    ]
