# Generated by Django 4.1.3 on 2023-01-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0046_alter_divider_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='link',
        ),
    ]
